export enum EventType {
  PRICE_UPDATE = 'PRICE_UPDATE',
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_APPROVED = 'ORDER_APPROVED',
  ORDER_REJECTED = 'ORDER_REJECTED',
  ORDER_STATUS_UPDATED = 'ORDER_STATUS_UPDATED',
  SYSTEM_MESSAGE = 'SYSTEM_MESSAGE'
}